# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3f21249cefff3d29475827cdfd91fa7866ae7bc980f4859992052ad680f7a63d49382fc5058944deb7e32b4a43f4b4cc272d6fde199771971b0e48cad3e84f58

test:
  secret_key_base: 03329f71c22e2f8f28bd4e3761539cc37dff7ec0dbd5124fe6d39deff99d3e266eee90ca045eec6fe70f8a74117faccda7ee9c708873459e734bdfaf6e98f75e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
